version: '2'

services:

  rocketchat:
    build:
      context: ./File
      dockerfile: dockerfile2
    user: root
    command: >
      bash -c "
        for i in \`seq 1 30\`; do
          node main.js &&
          s=\$? && break || s=\$?;
          echo \"Tried \$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit \$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - PORT_NAME=rocketchat
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0
      - MAIL_URL=smtp://smtp.email
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=ada2d48cw9d4a6wc78da3sd486ewwvt454gdf86h54
      - ADMIN_EMAIL=admin@example.com
      - PORT_NAME=rocketchat
    depends_on:
      - mongo-init-replica
    networks:
      A-network:
        ipv4_address: 10.10.1.2

  mongo:
    image: mongo:4.2.8
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    environment:
      - PORT_NAME=MongoDB
    networks:
      A-network:
        ipv4_address: 10.10.1.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-init-replica:
    image: mongo:4.2.8
    command: >
      bash -c "
        until mongo --host mongo --eval 'rs.status()' | grep 'myState' | grep -q 1; do
          mongo --host mongo --eval 'rs.initiate()';
          sleep 5;
        done"
    depends_on:
      - mongo
    restart: on-failure
    networks:
      A-network:
        ipv4_address: 10.10.1.5

  ubuntu:
    build:
      context: ./File
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "22:22"  # SSH
      - "20:20/tcp"  # FTP data transfer
      - "21:21/tcp"  # FTP control
      - "40000-40009:40000-40009/tcp"  # Passive FTP ports
    networks:
      A-network:
        ipv4_address: 10.10.1.3

networks:
  A-network:
    driver: bridge
    ipam:
      config:
        - subnet:  10.10.0.0/16